{
  "openapi": "3.0.1",
  "info": {
    "title": "Recommendation Service API",
    "description": "Recommendation Service",
    "version": "0.1.0"
  },
  "servers": [
    {
      "url": "http://localhost:8085/",
      "description": "Developer server"
    }
  ],
  "tags": [
    {
      "name": "Контроллер управления сервисом",
      "description": "Выполняет действия с сервисом"
    },
    {
      "name": "Контроллер рекомендаций продукта(ов) для клиента",
      "description": "Выполняет действия с рекомендациями продукта(ов) для клиента"
    },
    {
      "name": "Контроллер кеша рекомендаций",
      "description": "Выполняет действия с кешем рекомендаций"
    },
    {
      "name": "Контроллер продукта рекомендации",
      "description": "Выполняет действия с продуктом рекомендации"
    },
    {
      "name": "Контроллер динамических правил рекомендаций",
      "description": "Выполняет действия с динамическими правилами рекомендаций"
    }
  ],
  "paths": {
    "/rule": {
      "post": {
        "tags": [
          "Контроллер динамических правил рекомендаций"
        ],
        "summary": "Создание динамического правила рекомендации",
        "description": "Позволяет создать динамическое правило рекомендации",
        "operationId": "createDynamicRecommendation",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RecommendationsDTO"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object"
                }
              }
            }
          }
        }
      }
    },
    "/management/clear-caches": {
      "post": {
        "tags": [
          "Контроллер кеша рекомендаций"
        ],
        "summary": "Сброс кэша рекомендаций",
        "description": "Позволяет осуществить сброс кэша рекомендаций",
        "operationId": "clearCaches",
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/rule/{rule_id}": {
      "get": {
        "tags": [
          "Контроллер динамических правил рекомендаций"
        ],
        "summary": "Получение динамического правила рекомендации",
        "description": "Позволяет получить динамическое правило рекомендации",
        "operationId": "getDynamicRecommendation",
        "parameters": [
          {
            "name": "rule_id",
            "in": "path",
            "description": "Идентификатор динамического правила рекомендации",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Контроллер динамических правил рекомендаций"
        ],
        "summary": "Удаление динамического правила рекомендации",
        "description": "Позволяет удалить динамическое правило рекомендации",
        "operationId": "deleteDynamicRecommendation",
        "parameters": [
          {
            "name": "rule_id",
            "in": "path",
            "description": "Идентификатор динамического правила рекомендации",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object"
                }
              }
            }
          }
        }
      }
    },
    "/rule/stats": {
      "get": {
        "tags": [
          "Контроллер динамических правил рекомендаций"
        ],
        "summary": "Статистика срабатывания динамических правил рекомендаций",
        "description": "Позволяет получить статистику срабатываний динамических правил рекомендаций",
        "operationId": "getAllStatsCount",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object",
                  "additionalProperties": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "additionalProperties": {
                        "type": "object"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/rule/allRules": {
      "get": {
        "tags": [
          "Контроллер динамических правил рекомендаций"
        ],
        "summary": "Получение всех динамических правил рекомендаций",
        "description": "Позволяет получить все динамические правила рекомендаций",
        "operationId": "getAllDynamicRecommendations",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object"
                }
              }
            }
          }
        }
      }
    },
    "/recommendation/fixed/{user_id}": {
      "get": {
        "tags": [
          "Контроллер рекомендаций продукта(ов) для клиента"
        ],
        "summary": "Получение фиксированных рекомендаций продукта(ов) для клиента",
        "description": "Позволяет получить фиксированные рекомендации продукта(ов) для клиента",
        "operationId": "getUserFixedRecommendations",
        "parameters": [
          {
            "name": "user_id",
            "in": "path",
            "description": "Идентификатор клиента",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object"
                }
              }
            }
          }
        }
      }
    },
    "/recommendation/dynamic/{user_id}": {
      "get": {
        "tags": [
          "Контроллер рекомендаций продукта(ов) для клиента"
        ],
        "summary": "Получение динамических рекомендаций продукта(ов) для клиента",
        "description": "Позволяет получить динамические рекомендации продукта(ов) для клиента",
        "operationId": "getUserDynamicRecommendations",
        "parameters": [
          {
            "name": "user_id",
            "in": "path",
            "description": "Идентификатор клиента",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object"
                }
              }
            }
          }
        }
      }
    },
    "/product/{product_id}": {
      "get": {
        "tags": [
          "Контроллер продукта рекомендации"
        ],
        "summary": "Получение продукта рекомендации",
        "description": "Позволяет получить продукт рекомендации",
        "operationId": "getProduct",
        "parameters": [
          {
            "name": "product_id",
            "in": "path",
            "description": "Идентификатор продукта рекомендации",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object"
                }
              }
            }
          }
        }
      }
    },
    "/management/info": {
      "get": {
        "tags": [
          "Контроллер управления сервисом"
        ],
        "summary": "Возврат информации о сервисе",
        "description": "Позволяет осуществить возврат информации о сервисе",
        "operationId": "getBuildInfo",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/BuildProperties"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "RecommendationsDTO": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "Идентификатор правила рекомендации в БД",
            "format": "uuid"
          },
          "product_name": {
            "type": "string",
            "description": "Название рекомендации"
          },
          "product_id": {
            "type": "string",
            "description": "Идентификатор рекомендации в продакшн",
            "format": "uuid"
          },
          "product_text": {
            "type": "string",
            "description": "Описание рекомендации"
          },
          "rule": {
            "type": "array",
            "description": "Правила рекомендации",
            "items": {
              "$ref": "#/components/schemas/RulesDTO"
            }
          }
        },
        "description": "Динамическое правило рекомендации"
      },
      "RulesDTO": {
        "type": "object",
        "properties": {
          "query": {
            "type": "string",
            "description": "Название объекта запроса для правила рекомендации",
            "enum": [
              "USER_OF",
              "ACTIVE_USER_OF",
              "TRANSACTION_SUM_COMPARE",
              "TRANSACTION_SUM_COMPARE_DEPOSIT_WITHDRAW"
            ]
          },
          "arguments": {
            "type": "array",
            "description": "Аргументы объекта запроса для правила рекомендации",
            "items": {
              "type": "string",
              "description": "Аргументы объекта запроса для правила рекомендации"
            }
          },
          "negate": {
            "type": "boolean",
            "description": "Соответствие объекта запроса для правила рекомендации)"
          }
        },
        "description": "Сущность объекта запроса для правила рекомендации"
      },
      "BuildProperties": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "time": {
            "type": "string",
            "format": "date-time"
          },
          "version": {
            "type": "string"
          },
          "group": {
            "type": "string"
          },
          "artifact": {
            "type": "string"
          }
        }
      }
    }
  }
}